/*
 *  Spreadsheet by Madhawa

 
 */
package spreadsheet.gui;

import java.awt.Rectangle;

/**
 *
 * @author Madhawa
 */
public class SupportedFeaturesDialog extends javax.swing.JDialog {

    /**
     * Creates new form SupportedFeaturesDialog
     */
    public SupportedFeaturesDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //center
        this.setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtEvaluatorFeatures = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Supported Features");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtEvaluatorFeatures.setEditable(false);
        txtEvaluatorFeatures.setColumns(20);
        txtEvaluatorFeatures.setRows(5);
        txtEvaluatorFeatures.setText("List of Supported Features\n\n\nSupported DataTypes\n\tDecimal Numbers\n\tDateTime\n\tCurrency (Rs and $)\n\tBoolean (Logic)\n\tLabel (String)\n\t\n\tArrays (Via cell Ranges)\n\nSupported Operators\n\tAddition / Logical OR ( + )\n\tSubstraction ( - )\n\tMultiplication / Logical AND ( * )\n\tDivision ( / )\n\tPower / Logical XOR ( ^ )\n\t\n\tEquals ( = ) \n\tNot Equals ( <> ) \n\tLess Than ( < )\n\tLess Than or Equal ( <= )\n\tGreater Than ( > )\n\tGreater Than or Equal ( >= )\n\nSupported Functions (Formula)\n\tSum ( Cell Range)\n\tAvg ( Cell Range)\n\tAbs ( Expression or Cell Id) - Absolute Function\n\tIf ( condition, true_value, false_value)\n\tMax (Cell Range)\n\tMin (Cell Range)\n\n\t\n\t\n\t");
        jScrollPane2.setViewportView(txtEvaluatorFeatures);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Expression Evaluator Features", jPanel1);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("List of Supported Features\n\nAsynchronous Cell Expression Evaluation through multiple threads\nCell Highlights - Highlight cells relavent to formula being typed in addressbar or cell\nCell Picking - ONLY AVAILABLE WHEN AN EXPRESSION IS CHANGED IN FORMULA BAR\n\tSelect cells or cell ranges to append them to the expression being modified in formula bar\nCopy - Paste - Copy Paste operations with Automatic Expression Correction\n\nInsert/Delete Rows and Columns with automatic expression correction\nMultiple Cell Formatings - General, Numbers, Percentage\nCustomize Cell Style - Change Bold, Italic, FontSize, Font Family\nAutomatic Text Alignment in Cell based on DataType\n\nOpen a file given through command line arguement\nMultithreaded Open, Save and Export to CSV Support");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("GUI Features", jPanel2);

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        txtEvaluatorFeatures.scrollRectToVisible(new Rectangle(0,0,0,0));
    }//GEN-LAST:event_formWindowOpened

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea txtEvaluatorFeatures;
    // End of variables declaration//GEN-END:variables
}
